name: '.net code analysis'
on: [push, pull_request]

jobs:
  code-analysis:
    name: .NET Code Analysis runner
    runs-on: windows-latest

    steps:
      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Run NuGet restore
    - name: Run NuGet restore
      run: dotnet restore .\MineSweeper.sln

    # Run .NET Code Analysis
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        project: .\MineSweeper.sln
        build-breaking: true
        all-categories: all

    # Upload the analysis results file
    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: analysis_results.sarif
        path: ${{ steps.code-analysis.outputs.sarifFile }}