name: '.net code analysis'
on: [push, pull_request]

# Run on the latest version of Ubuntu
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      statuses: write

    steps:
    - uses: actions/checkout@v2

    # Run NuGet restore for each project/solution to analyze
    - name: Run NuGet restore
      run: dotnet restore <%path_to_project_or_solution%>

    # Run code analysis for all projects/solutions, such that code analysis violations break the build.
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        build-breaking: true