name: '.net code analysis'
on: [push, pull_request]

# Run on the latest version of Ubuntu
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      statuses: write

    # Checkout the repo into the workspace within the VM
    steps:
    - uses: actions/checkout@v2

    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        solution: MySolution.sln
        build-breaking: true
        all-categories: all